import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import test from "node:test";
import { promisify } from "node:util";

import { hydb, memoryStorage } from "@hyos/hydb";

import { createLiterateAgent, type LiterateAgent } from "../src/agent.js";
import { decodeActivityEvent, encodeActivityEvent } from "../src/activity.js";
import { editLiterateDiff } from "../src/document.js";
import type { LiterateDiff, SessionListItem } from "../src/domain.js";
import type { GatewayMessage, GatewayTransport } from "../src/gateway.js";
import { hyagentSchema } from "../src/model.js";
import { createProjectTools, type ProjectTools } from "../src/project-tools.js";
import { createHyagentStore } from "../src/store.js";
import { createHyagentRouter } from "../src/trpc.js";
import { shouldShowWorkspacePicker } from "../src/workspace-state.js";

const exec = promisify(execFile);

const proposedDocument: LiterateDiff = {
  summary: "Explain the seam before proposing the code.",
  blocks: [
    {
      id: "intent",
      kind: "prose",
      title: "Keep review in the loop",
      body: "The document changes while the model works.",
    },
    {
      id: "change",
      kind: "apply_patch",
      repository: "workspace",
      title: "Change one file",
      rationale: "This is the smallest testable proposal.",
      patch:
        "diff --git a/a.txt b/a.txt\n--- a/a.txt\n+++ b/a.txt\n@@ -1 +1 @@\n-before\n+after\n",
    },
  ],
  generatedIgnores: [],
};

async function setup() {
  const storage = await memoryStorage({ schema: hyagentSchema });
  const database = await hydb.database({ schema: hyagentSchema, storage });
  return { database, store: createHyagentStore(database) };
}

function fakeProject(overrides: Partial<ProjectTools> = {}): ProjectTools {
  return {
    repositoryNames: () => ["workspace"],
    repositorySpecs: () => [{ name: "workspace", root: "/workspace" }],
    configureRepositories: async () => undefined,
    prepareRepositories: async (repositories) => repositories,
    initialize: async () => undefined,
    readFile: async () => "",
    runCommand: async () => "",
    syncPatches: async () => undefined,
    checkConsistency: async () => [],
    commit: async () => [],
    enrichDocument: async (document) => document,
    ...overrides,
  };
}

function fakeAgent(overrides: Partial<LiterateAgent> = {}): LiterateAgent {
  return {
    run: async () => proposedDocument,
    writeCommitMessages: async () => ({
      workspace: "feat: apply literate change",
    }),
    ...overrides,
  };
}

test("document operations preserve stable blocks and generated ignores", () => {
  const first = editLiterateDiff(null, [
    { type: "set_summary", summary: "Live draft" },
    {
      type: "insert_block",
      block: {
        id: "overview",
        kind: "prose",
        title: "Overview",
        body: "Start with intent.",
      },
    },
  ]);
  const second = editLiterateDiff(first, [
    {
      type: "replace_block",
      id: "overview",
      block: {
        id: "overview",
        kind: "prose",
        title: "Overview",
        body: "Keep the intent current.",
      },
    },
    {
      type: "set_generated_ignores",
      entries: [
        {
          repository: "workspace",
          path: "coverage/**",
          reason: "Generated by tests",
        },
      ],
    },
  ]);

  assert.equal(second.blocks[0]?.id, "overview");
  assert.equal(second.generatedIgnores[0]?.path, "coverage/**");
});

test("a configured workspace opens an empty thread", () => {
  assert.equal(shouldShowWorkspacePicker(true), false);
  assert.equal(shouldShowWorkspacePicker(false), true);
});

test("hydb stores every incremental literate-diff revision", async () => {
  const { database, store } = await setup();
  try {
    const session = await store.createSession("Review a change");
    await store.saveRevision(session.id, {
      summary: "First pass",
      blocks: proposedDocument.blocks.slice(0, 1),
      generatedIgnores: [],
    });
    await store.saveRevision(session.id, proposedDocument);
    await store.setStatus(session.id, "ready");

    const snapshot = await store.getSession(session.id);
    assert.equal(snapshot.status, "ready");
    assert.equal(snapshot.revision?.number, 2);
    assert.equal(snapshot.revision?.blocks.length, 2);
  } finally {
    await database.close();
  }
});

test("the custom loop publishes document edits before it finishes", async () => {
  const { database, store } = await setup();
  const responses: GatewayMessage[] = [
    {
      role: "assistant",
      content: null,
      tool_calls: [
        {
          id: "overview",
          function: {
            name: "edit_literate_diff",
            arguments: JSON.stringify({
              operations: [
                { type: "set_summary", summary: "Understand the change" },
                {
                  type: "insert_block",
                  block: proposedDocument.blocks[0],
                },
              ],
            }),
          },
        },
      ],
    },
    {
      role: "assistant",
      content: null,
      tool_calls: [
        {
          id: "patch",
          function: {
            name: "edit_literate_diff",
            arguments: JSON.stringify({
              operations: [
                { type: "set_summary", summary: proposedDocument.summary },
                {
                  type: "insert_block",
                  after: "intent",
                  block: proposedDocument.blocks[1],
                },
              ],
            }),
          },
        },
      ],
    },
    { role: "assistant", content: "The first pass is ready." },
  ];
  const gateway: GatewayTransport = {
    async complete() {
      const response = responses.shift();
      if (!response) throw new Error("Unexpected model step");
      return response;
    },
  };
  const synchronized: number[] = [];
  const project = fakeProject({
    async syncPatches(_previous, next) {
      synchronized.push(next.blocks.length);
    },
  });
  try {
    const session = await store.createSession("Review a change");
    const agent = createLiterateAgent({ store, project, gateway });
    await agent.run(session.id, "Make the change understandable");

    const snapshot = await store.getSession(session.id);
    assert.deepEqual(synchronized, [1, 2]);
    assert.equal(snapshot.revision?.number, 2);
    assert.equal(snapshot.status, "ready");
    assert.equal(
      snapshot.messages.filter((message) => message.role === "agent").at(-1)
        ?.content,
      "The first pass is ready.",
    );
    assert.deepEqual(
      snapshot.messages
        .map((message) => decodeActivityEvent(message.content)?.status)
        .filter(Boolean),
      [
        "working",
        "working",
        "working",
        "working",
        "working",
        "working",
        "complete",
      ],
    );
  } finally {
    await database.close();
  }
});

test("the custom loop becomes visible before project inspection finishes", async () => {
  const { database, store } = await setup();
  let releaseInspection!: () => void;
  let inspectionStarted!: () => void;
  const inspection = new Promise<void>((resolve) => {
    releaseInspection = resolve;
  });
  const started = new Promise<void>((resolve) => {
    inspectionStarted = resolve;
  });
  const project = fakeProject({
    async initialize() {
      inspectionStarted();
      await inspection;
    },
  });
  const gateway: GatewayTransport = {
    async complete() {
      throw new Error("Stop after inspection");
    },
  };
  try {
    const session = await store.createSession("Review a change");
    const agent = createLiterateAgent({ store, project, gateway });
    const run = agent.run(session.id, "Start the first pass");
    await started;

    const running = await store.getSession(session.id);
    assert.equal(running.status, "running");
    assert.equal(
      [...running.messages].reverse().find((message) => message.role === "user")
        ?.content,
      "Start the first pass",
    );
    assert.equal(
      decodeActivityEvent(running.messages.at(-1)?.content ?? "")?.status,
      "working",
    );

    releaseInspection();
    await assert.rejects(run, /Stop after inspection/);
  } finally {
    releaseInspection();
    await database.close();
  }
});

test("session changes stream from Hydb subscriptions", async () => {
  const { database, store } = await setup();
  const abort = new AbortController();
  try {
    const session = await store.createSession("Watch a change");
    const iterator = store
      .subscribeSession(session.id, abort.signal)
      [Symbol.asyncIterator]();
    const initial = await iterator.next();
    assert.equal(initial.value?.id, session.id);

    await store.appendMessage(session.id, "user", "Stream this update");
    let updated = await iterator.next();
    while (
      !updated.done &&
      !updated.value.messages.some(
        (message) => message.content === "Stream this update",
      )
    ) {
      updated = await iterator.next();
    }
    assert.equal(updated.done, false);
    assert.equal(updated.value?.messages.at(-1)?.content, "Stream this update");
    abort.abort();
    await iterator.return?.();
  } finally {
    abort.abort();
    await database.close();
  }
});

test("the session index streams creation and title changes", async () => {
  const { database, store } = await setup();
  const abort = new AbortController();
  try {
    const first = await store.createSession("First task");
    const iterator = store
      .subscribeSessions(abort.signal)
      [Symbol.asyncIterator]();
    assert.deepEqual(
      (await iterator.next()).value?.map((item: SessionListItem) => item.id),
      [first.id],
    );

    const second = await store.createSession("New agent task");
    let latest: SessionListItem[] = (await iterator.next()).value ?? [];
    while (!latest.some((item: SessionListItem) => item.id === second.id)) {
      latest = (await iterator.next()).value ?? [];
    }
    assert.equal(latest[0]?.id, second.id);

    await store.setTitle(second.id, "A useful session title");
    do {
      latest = (await iterator.next()).value ?? [];
    } while (latest[0]?.title !== "A useful session title");
    assert.equal(latest[0]?.title, "A useful session title");

    await store.archiveSession(first.id);
    do {
      latest = (await iterator.next()).value ?? [];
    } while (latest.some((item) => item.id === first.id));
    assert.deepEqual(
      latest.map((item) => item.id),
      [second.id],
    );
    assert.deepEqual((await store.getSession(first.id)).messages, []);
    abort.abort();
    await iterator.return?.();
  } finally {
    abort.abort();
    await database.close();
  }
});

test("recent repositories prefer source checkouts over generated worktrees", async () => {
  const { database, store } = await setup();
  try {
    const first = await store.createSession("First task");
    await store.saveWorkspace(first.id, [
      { name: "project", root: "/managed/project-worktree" },
    ]);
    await store.saveSourceRepositories(first.id, [
      { name: "project", root: "/code/project" },
    ]);
    const second = await store.createSession("Second task");
    await store.saveSourceRepositories(second.id, [
      { name: "other", root: "/code/other" },
      { name: "project", root: "/code/project" },
    ]);

    assert.deepEqual(await store.recentRepositories(), [
      { name: "other", root: "/code/other" },
      { name: "project", root: "/code/project" },
    ]);
    assert.deepEqual((await store.getSession(second.id)).messages, []);
  } finally {
    await database.close();
  }
});

test("the custom loop replaces stale consistency warnings", async () => {
  const { database, store } = await setup();
  let gatewayMessages: GatewayMessage[] = [];
  const gateway: GatewayTransport = {
    async complete(request) {
      gatewayMessages = request.messages;
      throw new Error("Captured model context");
    },
  };
  const project = fakeProject({
    async checkConsistency() {
      return [
        {
          repository: "project",
          path: "generated/**",
          message:
            "project:generated/** contains 42 changes outside the literate diff",
        },
      ];
    },
  });
  try {
    const session = await store.createSession("Review a change");
    await store.appendMessage(
      session.id,
      "system",
      "WORKTREE_INCONSISTENT: stale oversized warning",
    );
    await store.appendMessage(
      session.id,
      "system",
      encodeActivityEvent({
        runId: "old-run",
        status: "complete",
        summary: "Old internal activity",
      }),
    );
    const agent = createLiterateAgent({ store, project, gateway });
    await assert.rejects(
      agent.run(session.id, "Continue the work"),
      /Captured model context/,
    );

    const context = gatewayMessages
      .map((message) => message.content)
      .join("\n");
    assert.doesNotMatch(context, /stale oversized warning/);
    assert.doesNotMatch(context, /Old internal activity/);
    assert.match(context, /generated\/\*\* contains 42 changes/);
  } finally {
    await database.close();
  }
});

async function git(root: string, ...args: string[]) {
  await exec("git", args, { cwd: root });
}

async function createRepository(name: string) {
  const root = await mkdtemp(join(tmpdir(), `hyagent-${name}-`));
  await git(root, "init", "-q");
  await git(root, "config", "user.email", "hyagent@example.test");
  await git(root, "config", "user.name", "Hyagent Test");
  await writeFile(join(root, "state.txt"), "one\ntwo\n");
  await git(root, "add", "state.txt");
  await git(root, "commit", "-qm", "baseline");
  return root;
}

test("a repository with no commits can be opened", async () => {
  const root = await mkdtemp(join(tmpdir(), "hyagent-unborn-"));
  try {
    await git(root, "init", "-q");
    await writeFile(join(root, "README.md"), "# New project\n");

    const project = createProjectTools([{ name: "new-project", root }]);
    await project.initialize();

    assert.deepEqual(
      (await project.checkConsistency([])).map(({ path }) => path),
      [],
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("consistency warnings collapse large changed folders", async () => {
  const root = await createRepository("compact-warnings");
  try {
    const project = createProjectTools([{ name: "project", root }]);
    await project.initialize();
    await mkdir(join(root, "generated"));
    await Promise.all(
      Array.from({ length: 11 }, (_, index) =>
        writeFile(join(root, "generated", `${index}.json`), "{}\n"),
      ),
    );

    const warnings = await project.checkConsistency([]);
    assert.equal(warnings.length, 1);
    assert.equal(warnings[0]?.path, "generated/**");
    assert.match(warnings[0]?.message ?? "", /contains 11 changes/);
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

function patchBlock(
  id: string,
  repository: string,
  hunk: string,
): LiterateDiff["blocks"][number] {
  return {
    id,
    kind: "apply_patch",
    repository,
    title: id,
    rationale: `Apply ${id}`,
    patch: `diff --git a/state.txt b/state.txt\n--- a/state.txt\n+++ b/state.txt\n${hunk}\n`,
  };
}

test("patch replay and consistency are scoped across repositories", async () => {
  const firstRoot = await createRepository("first");
  const secondRoot = await createRepository("second");
  try {
    const project = createProjectTools([
      { name: "first", root: firstRoot },
      { name: "second", root: secondRoot },
    ]);
    await project.initialize();

    const patchA = patchBlock(
      "a",
      "first",
      "@@ -1,2 +1,2 @@\n-one\n+ONE\n two",
    );
    const patchB = patchBlock(
      "b",
      "first",
      "@@ -1,2 +1,2 @@\n ONE\n-two\n+TWO",
    );
    const patchOther = patchBlock(
      "other",
      "second",
      "@@ -1,2 +1,2 @@\n-one\n+OTHER\n two",
    );
    const first: LiterateDiff = {
      summary: "Cross-repository change",
      blocks: [patchA, patchOther, patchB],
      generatedIgnores: [],
    };
    await project.syncPatches(null, first);
    assert.equal(
      await readFile(join(firstRoot, "state.txt"), "utf8"),
      "ONE\nTWO\n",
    );
    assert.equal(
      await readFile(join(secondRoot, "state.txt"), "utf8"),
      "OTHER\ntwo\n",
    );

    const revisedA = patchBlock(
      "a",
      "first",
      "@@ -1,2 +1,2 @@\n-one\n+UNO\n two",
    );
    const broken: LiterateDiff = {
      ...first,
      blocks: [revisedA, patchOther, patchB],
    };
    await assert.rejects(() => project.syncPatches(first, broken), /at b/);
    assert.equal(
      await readFile(join(firstRoot, "state.txt"), "utf8"),
      "ONE\nTWO\n",
    );

    const revisedB = patchBlock(
      "b",
      "first",
      "@@ -1,2 +1,2 @@\n UNO\n-two\n+TWO",
    );
    const repaired: LiterateDiff = {
      ...first,
      blocks: [revisedA, patchOther, revisedB],
    };
    await project.syncPatches(first, repaired);
    assert.equal(
      await readFile(join(firstRoot, "state.txt"), "utf8"),
      "UNO\nTWO\n",
    );

    await writeFile(join(secondRoot, "coverage.txt"), "generated\n");
    const warnings = await project.checkConsistency([]);
    assert.deepEqual(
      warnings.map(({ repository, path }) => ({ repository, path })),
      [{ repository: "second", path: "coverage.txt" }],
    );
    assert.deepEqual(
      await project.checkConsistency([
        {
          repository: "second",
          path: "coverage.txt",
          reason: "Generated by validation",
        },
      ]),
      [],
    );
  } finally {
    await Promise.all([
      rm(firstRoot, { recursive: true, force: true }),
      rm(secondRoot, { recursive: true, force: true }),
    ]);
  }
});

test("project commits only literate-diff paths with the supplied message", async () => {
  const root = await createRepository("commit");
  try {
    const project = createProjectTools([{ name: "project", root }]);
    await project.initialize();
    const document: LiterateDiff = {
      summary: "Update state",
      blocks: [
        patchBlock("state", "project", "@@ -1,2 +1,2 @@\n-one\n+ONE\n two"),
      ],
      generatedIgnores: [
        {
          repository: "project",
          path: "generated.txt",
          reason: "Validation output",
        },
      ],
    };
    await project.syncPatches(null, document);
    await writeFile(join(root, "generated.txt"), "generated\n");
    await git(root, "add", "generated.txt");

    const commits = await project.commit(document, {
      project: "feat: update immutable state",
    });

    assert.equal(commits.length, 1);
    assert.equal(
      (
        await exec("git", ["log", "-1", "--pretty=%B"], { cwd: root })
      ).stdout.trim(),
      "feat: update immutable state",
    );
    assert.equal(
      (
        await exec("git", ["diff", "--cached", "--name-only"], {
          cwd: root,
        })
      ).stdout.trim(),
      "generated.txt",
    );
  } finally {
    await rm(root, { recursive: true, force: true });
  }
});

test("project can prepare an isolated worktree and copy included files", async () => {
  const root = await createRepository("worktree-source");
  const worktreeRoot = await mkdtemp(join(tmpdir(), "hyagent-worktrees-"));
  try {
    await writeFile(join(root, ".gitignore"), ".env\n");
    await writeFile(join(root, ".worktreeinclude"), ".env\n");
    await writeFile(join(root, ".env"), "LOCAL_ONLY=test\n");
    await git(root, "add", ".gitignore", ".worktreeinclude");
    await git(root, "commit", "-qm", "configure worktrees");
    const project = createProjectTools([{ name: "project", root }], {
      worktreeRoot,
    });

    const prepared = await project.prepareRepositories(
      [{ name: "project", root }],
      "worktree",
    );

    assert.notEqual(prepared[0]?.root, root);
    assert.equal(
      await readFile(join(prepared[0]!.root, ".env"), "utf8"),
      "LOCAL_ONLY=test\n",
    );
    assert.match(
      (
        await exec("git", ["branch", "--show-current"], {
          cwd: prepared[0]!.root,
        })
      ).stdout.trim(),
      /^hyagent\/project-/,
    );
  } finally {
    await Promise.all([
      rm(root, { recursive: true, force: true }),
      rm(worktreeRoot, { recursive: true, force: true }),
    ]);
  }
});

test("the agent writes focused commit messages for affected repositories", async () => {
  const { database, store } = await setup();
  const requests: string[] = [];
  const gateway: GatewayTransport = {
    async complete(request) {
      requests.push(request.messages.at(-1)?.content ?? "");
      return {
        role: "assistant",
        content: "```text\nfeat: explain the project seam\n```",
      };
    },
  };
  try {
    const agent = createLiterateAgent({
      store,
      project: fakeProject(),
      gateway,
    });
    const messages = await agent.writeCommitMessages(proposedDocument);
    assert.deepEqual(messages, {
      workspace: "feat: explain the project seam",
    });
    assert.equal(requests.length, 1);
    assert.match(requests[0] ?? "", /Change one file/);
  } finally {
    await database.close();
  }
});

test("acceptance verifies consistency without reapplying patches", async () => {
  const { database, store } = await setup();
  let checks = 0;
  let committedMessage = "";
  const project = fakeProject({
    async checkConsistency() {
      checks += 1;
      return [];
    },
    async commit(_document, messages) {
      committedMessage = messages.workspace ?? "";
      return [
        {
          repository: "workspace",
          hash: "1234567890abcdef",
          message: committedMessage,
        },
      ];
    },
  });
  const agent = fakeAgent();
  try {
    const router = createHyagentRouter({ store, project, agent });
    const caller = router.createCaller({});
    const session = await caller.session.bootstrap();
    assert.equal(session.revision, null);
    await store.saveRevision(session.id, proposedDocument);
    const committed = await caller.session.commit({ id: session.id });
    assert.equal(checks, 1);
    assert.equal(committedMessage, "feat: apply literate change");
    assert.equal(committed.status, "committed");
  } finally {
    await database.close();
  }
});

test("feedback starts the agent without holding the mutation open", async () => {
  const { database, store } = await setup();
  let release!: () => void;
  let completed = false;
  const blocked = new Promise<void>((resolve) => {
    release = resolve;
  });
  const agent = fakeAgent({
    async run() {
      await blocked;
      completed = true;
      return proposedDocument;
    },
  });
  try {
    const router = createHyagentRouter({
      store,
      project: fakeProject(),
      agent,
    });
    const caller = router.createCaller({});
    const session = await caller.session.bootstrap();
    const result = await caller.session.feedback({
      id: session.id,
      feedback: "Start working",
    });
    assert.deepEqual(result, { accepted: true });
    assert.equal(completed, false);
    release();
  } finally {
    release();
    await database.close();
  }
});

test("a task is persisted only after workspace preparation succeeds", async () => {
  const { database, store } = await setup();
  let shouldFail = true;
  const project = fakeProject({
    async prepareRepositories(repositories) {
      if (shouldFail) throw new Error("Could not prepare workspace");
      return repositories;
    },
  });
  try {
    const router = createHyagentRouter({
      store,
      project,
      agent: fakeAgent(),
    });
    const caller = router.createCaller({});
    assert.equal(await caller.session.initial(), null);
    await assert.rejects(
      caller.session.start({
        repositories: [{ name: "project", root: "/code/project" }],
        mode: "worktree",
        prompt: "Build the first change",
      }),
      /Could not prepare workspace/,
    );
    assert.deepEqual(await caller.session.list(), []);

    shouldFail = false;
    const started = await caller.session.start({
      repositories: [{ name: "project", root: "/code/project" }],
      mode: "checkout",
      prompt: "Build the first change",
    });
    assert.equal(started.session.title, "Build the first change");
    assert.equal((await caller.session.list()).length, 1);
    assert.deepEqual(await caller.workspace.recent(), [
      { name: "project", root: "/code/project" },
    ]);
  } finally {
    await database.close();
  }
});

test("a task starts empty and configures repositories from folder selection", async () => {
  const { database, store } = await setup();
  const configured: string[][] = [];
  let specs: Array<{ name: string; root: string }> = [];
  const project = fakeProject({
    repositoryNames: () => specs.map((repository) => repository.name),
    repositorySpecs: () => specs,
    async configureRepositories(repositories) {
      specs = [...repositories];
      configured.push(repositories.map((repository) => repository.root));
    },
  });
  const agent = fakeAgent();
  const folderPicker = {
    choose: async () => ({ name: "project", root: "/code/project" }),
  };
  try {
    const router = createHyagentRouter({
      store,
      project,
      agent,
      folderPicker,
      agentConfigured: false,
    });
    const caller = router.createCaller({});
    const session = await caller.session.bootstrap();
    assert.equal(session.revision, null);
    assert.deepEqual(session.messages, []);
    assert.equal((await caller.health()).agentConfigured, false);
    assert.deepEqual(await caller.workspace.chooseFolder(), {
      name: "project",
      root: "/code/project",
    });

    const started = await caller.workspace.configure({
      repositories: [{ name: "project", root: "/code/project" }],
    });
    assert.deepEqual(configured, [["/code/project"]]);
    assert.equal(started.session.revision, null);
    assert.match(started.session.messages[0]?.content ?? "", /project/);
  } finally {
    await database.close();
  }
});

test("a restarted router restores its unfinished session and workspace", async () => {
  const { database, store } = await setup();
  const agent = fakeAgent();
  let firstSpecs: Array<{ name: string; root: string }> = [];
  const firstProject = fakeProject({
    repositoryNames: () => firstSpecs.map(({ name }) => name),
    repositorySpecs: () => firstSpecs,
    async configureRepositories(repositories) {
      firstSpecs = [...repositories];
    },
  });
  try {
    const firstRouter = createHyagentRouter({
      store,
      project: firstProject,
      agent,
    });
    const firstCaller = firstRouter.createCaller({});
    const original = await firstCaller.session.bootstrap();
    await firstCaller.workspace.configure({
      repositories: [{ name: "project", root: "/code/project" }],
    });

    let restoredSpecs: Array<{ name: string; root: string }> = [];
    const restartedProject = fakeProject({
      repositoryNames: () => restoredSpecs.map(({ name }) => name),
      repositorySpecs: () => restoredSpecs,
      async configureRepositories(repositories) {
        restoredSpecs = [...repositories];
      },
    });
    const restartedRouter = createHyagentRouter({
      store,
      project: restartedProject,
      agent,
    });
    const restartedCaller = restartedRouter.createCaller({});

    const restored = await restartedCaller.session.bootstrap();
    assert.equal(restored.id, original.id);
    assert.deepEqual(await restartedCaller.workspace.current(), [
      { name: "project", root: "/code/project" },
    ]);
  } finally {
    await database.close();
  }
});

test("a legacy session with a revision can reattach its missing workspace", async () => {
  const { database, store } = await setup();
  let specs: Array<{ name: string; root: string }> = [];
  const project = fakeProject({
    repositoryNames: () => specs.map(({ name }) => name),
    repositorySpecs: () => specs,
    async configureRepositories(repositories) {
      specs = [...repositories];
    },
  });
  try {
    const session = await store.createSession("Existing task");
    await store.saveRevision(session.id, proposedDocument);
    const router = createHyagentRouter({
      store,
      project,
      agent: fakeAgent(),
    });
    const caller = router.createCaller({});

    const restored = await caller.session.bootstrap();
    assert.equal(restored.id, session.id);
    await caller.workspace.configure({
      repositories: [{ name: "project", root: "/code/project" }],
    });
    assert.deepEqual(await store.getWorkspace(session.id), [
      { name: "project", root: "/code/project" },
    ]);
  } finally {
    await database.close();
  }
});
